"""feature: new models for modular resume screening

Revision ID: 0681d760642c
Revises: 78418fcc939e
Create Date: 2025-05-15 17:43:47.910460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0681d760642c'
down_revision: Union[str, None] = '78418fcc939e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_screening_criterias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_criteria_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criteria_id', sa.Integer(), nullable=True),
    sa.Column('resume_field', sa.String(), nullable=False),
    sa.Column('prompt_template', sa.String(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['criteria_id'], ['resume_screening_criterias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_criteria_fields')
    op.drop_table('resume_screening_criterias')
    # ### end Alembic commands ###
