"""Fix application model enum problem

Revision ID: 134955f1f2ce
Revises: f05bd6b646a3
Create Date: 2025-04-15 22:37:14.512158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134955f1f2ce'
down_revision: Union[str, None] = 'f05bd6b646a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE applicationstatus ADD VALUE 'REVIEW'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE applicationstatus RENAME TO applicationstatus_old")
    op.execute("CREATE TYPE applicationstatus AS ENUM('ACTIVE', 'ACCEPTED', 'REJECTED')")
    op.execute((
        "ALTER TABLE applications ALTER COLUMN status TYPE applicationstatus USING "
        "status::text::applicationstatus"
    ))
    op.execute("DROP TYPE applicationstatus_old")
    pass
    # ### end Alembic commands ###
