"""feature: added is_admin field to HrSpecialist model

Revision ID: 18c3c01947e8
Revises: 78418fcc939e
Create Date: 2025-05-25 19:27:48.170077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c3c01947e8'
down_revision: Union[str, None] = '78418fcc939e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_specialists', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hr_specialists', 'is_admin')
    # ### end Alembic commands ###
