"""feature: added is_admin field to HrSpecialist model

Revision ID: 18c3c01947e8
Revises: 78418fcc939e
Create Date: 2025-05-25 19:27:48.170077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c3c01947e8'
down_revision: Union[str, None] = '78418fcc939e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_criteria_fields')
    op.drop_table('resume_screening_criterias')
    op.add_column('hr_specialists', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hr_specialists', 'is_admin')
    op.create_table('resume_screening_criterias',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('resume_screening_criterias_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('vacancy_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], name='resume_screening_criterias_vacancy_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='resume_screening_criterias_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('resume_criteria_fields',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('criteria_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resume_field', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prompt_template', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['criteria_id'], ['resume_screening_criterias.id'], name='resume_criteria_fields_criteria_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='resume_criteria_fields_pkey')
    )
    # ### end Alembic commands ###
