"""feature: added modular screening related fields to BotQuestion model

Revision ID: 213b5f5752f6
Revises: a7e6c86056ad
Create Date: 2025-05-08 15:50:26.296712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '213b5f5752f6'
down_revision: Union[str, None] = 'a7e6c86056ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_questions', sa.Column('is_for_screening', sa.Boolean(), nullable=True))
    op.add_column('bot_questions', sa.Column('screening_criteria', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_questions', 'screening_criteria')
    op.drop_column('bot_questions', 'is_for_screening')
    # ### end Alembic commands ###
