"""KAN-77: Changed HrNotification model: added FK to Application

Revision ID: 2fead14060dc
Revises: d922a4ba94cc
Create Date: 2025-04-23 15:42:34.486055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fead14060dc'
down_revision: Union[str, None] = 'd922a4ba94cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_notifications', sa.Column('application_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hr_notifications', 'applications', ['application_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hr_notifications', type_='foreignkey')
    op.drop_column('hr_notifications', 'application_id')
    # ### end Alembic commands ###
