"""Added choices column to BotQuestions model

Revision ID: 3942de41b485
Revises: 134955f1f2ce
Create Date: 2025-04-16 15:23:26.256046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3942de41b485'
down_revision: Union[str, None] = '134955f1f2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_questions', sa.Column('choices', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_questions', 'choices')
    # ### end Alembic commands ###
