"""KAN-66: Changes to Resume model. Reason: in resume.py

Revision ID: 3d7e83bf5fff
Revises: 92cbc7bb4fcd
Create Date: 2025-05-01 15:49:04.172417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d7e83bf5fff'
down_revision: Union[str, None] = '92cbc7bb4fcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'parsed_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('parsed_text', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
