"""Added work_mode to HrSpecialist table

Revision ID: 5065704ab96e
Revises: 9d5c479dddf4
Create Date: 2025-04-09 14:45:46.648012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5065704ab96e'
down_revision: Union[str, None] = '9d5c479dddf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_specialists', sa.Column('work_mode', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hr_specialists', 'work_mode')
    # ### end Alembic commands ###
