"""Removed current_step in BotInteraction. Reason: deprecated fied

Revision ID: 7e63ca756097
Revises: d54d626526f3
Create Date: 2025-04-21 13:23:04.131778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e63ca756097'
down_revision: Union[str, None] = 'd54d626526f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_interactions', 'current_step')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_interactions', sa.Column('current_step', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
