"""core: remove deprecated work_mode from HrSpecialist model

Revision ID: 825b5603d08d
Revises: 3d7e83bf5fff
Create Date: 2025-05-05 18:50:21.120882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '825b5603d08d'
down_revision: Union[str, None] = '3d7e83bf5fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hr_specialists', 'work_mode')
    op.create_unique_constraint(None, 'resumes', ['application_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resumes', type_='unique')
    op.add_column('hr_specialists', sa.Column('work_mode', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
