"""KAN-66: Added resume_link field to Resume model

Revision ID: 8341becfbf27
Revises: 8ce31435dd15
Create Date: 2025-04-30 12:58:38.049744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8341becfbf27'
down_revision: Union[str, None] = '8ce31435dd15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('resume_link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'resume_link')
    # ### end Alembic commands ###
