"""KAN-73: Added Token field to Application model

Revision ID: 99f992d30b19
Revises: 7e63ca756097
Create Date: 2025-04-22 13:16:32.412770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99f992d30b19'
down_revision: Union[str, None] = '7e63ca756097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('auth_token', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('token_expiry', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_applications_auth_token'), 'applications', ['auth_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_auth_token'), table_name='applications')
    op.drop_column('applications', 'token_expiry')
    op.drop_column('applications', 'auth_token')
    # ### end Alembic commands ###
