"""KAN-66: Changes to HrSpecialist and Application models. Made FK connections

Revision ID: 9c8a7261d6d9
Revises: 20640ee10671
Create Date: 2025-04-30 21:17:35.868661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8a7261d6d9'
down_revision: Union[str, None] = '20640ee10671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('hr_specialist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'applications', 'hr_specialists', ['hr_specialist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'hr_specialist_id')
    # ### end Alembic commands ###
