"""Add hr_specialist_id foreign key

Revision ID: 9d5c479dddf4
Revises: 277cdeafe379
Create Date: 2025-04-03 16:52:29.066013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d5c479dddf4'
down_revision: Union[str, None] = '277cdeafe379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_notifications', sa.Column('hr_specialist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hr_notifications', 'hr_specialists', ['hr_specialist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hr_notifications', type_='foreignkey')
    op.drop_column('hr_notifications', 'hr_specialist_id')
    # ### end Alembic commands ###
