"""feature: added consent field to BotInteraction model

Revision ID: ccb1ce9c3a90
Revises: 213b5f5752f6
Create Date: 2025-05-14 16:05:20.789488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccb1ce9c3a90'
down_revision: Union[str, None] = '213b5f5752f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_interactions', sa.Column('personal_data_consent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_interactions', 'personal_data_consent')
    # ### end Alembic commands ###
