"""Removed deprecated CandidateAnswer model / Reason: described in model script file

Revision ID: d54d626526f3
Revises: 3942de41b485
Create Date: 2025-04-17 14:43:12.824717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd54d626526f3'
down_revision: Union[str, None] = '3942de41b485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_answers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_answers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gigachat_response', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name='candidate_answers_application_id_fkey'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name='candidate_answers_candidate_id_fkey'),
    sa.ForeignKeyConstraint(['question_id'], ['bot_questions.id'], name='candidate_answers_question_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='candidate_answers_pkey')
    )
    # ### end Alembic commands ###
