"""KAN-77: Changed HrNotification model: rework sent_data

Revision ID: d922a4ba94cc
Revises: e896800f8415
Create Date: 2025-04-23 14:52:51.378613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd922a4ba94cc'
down_revision: Union[str, None] = 'e896800f8415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_notifications', sa.Column('vacancy_id', sa.Integer(), nullable=True))
    op.add_column('hr_notifications', sa.Column('analysis_score', sa.Float(), nullable=True))
    op.add_column('hr_notifications', sa.Column('final_decision', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'hr_notifications', 'vacancies', ['vacancy_id'], ['id'])
    op.drop_column('hr_notifications', 'sent_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_notifications', sa.Column('sent_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'hr_notifications', type_='foreignkey')
    op.drop_column('hr_notifications', 'final_decision')
    op.drop_column('hr_notifications', 'analysis_score')
    op.drop_column('hr_notifications', 'vacancy_id')
    # ### end Alembic commands ###
