"""Added UNDER_REVIEW enum top Application

Revision ID: f05bd6b646a3
Revises: 6f1c93a4d166
Create Date: 2025-04-15 21:39:38.730659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f05bd6b646a3'
down_revision: Union[str, None] = '6f1c93a4d166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
